"""Typed request/response structures for the ground-side maintenance copilot.

The deterministic AeroMind pipeline owns every technical value (fault, confidence, RUL, risk,
decision, part, window). The LLM may only supply explanatory *text* (``AdvisoryExplanation``) and,
for work orders, an inspection checklist and notes. Everything else in a response is copied from
the deterministic context by code, never taken from model output.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field

AI_LABEL = "AI-generated assistance — technician review required."
TEMPLATE_LABEL = "Template response generated by rules, not by an LLM. Technician review required."
SIM_NOTE = "All aircraft and data are simulated. Prototype policy, not a certified maintenance procedure."

# LLM STATUS shown in the UI.
ONLINE, LOCAL, FALLBACK, UNAVAILABLE = "ONLINE", "LOCAL", "FALLBACK", "UNAVAILABLE"

TASKS = ("explain_alert", "summarize_aircraft", "why_fault", "explain_rul", "maintenance_assist",
         "work_order", "what_if", "fleet_summary")

MAX_QUESTION_CHARS = 500
MAX_TEXT_CHARS = 1500
MAX_ITEM_CHARS = 500
MAX_ITEMS = 8


class SchemaError(ValueError):
    """Model output that does not match the expected structure."""


@dataclass(frozen=True)
class CopilotRequest:
    task: str = ""  # one of TASKS; inferred from ``question`` when empty
    tail: str = ""
    question: str = ""
    hours_to_next_check: float | None = None  # what-if: next check this many FH from now

    def cleaned_question(self) -> str:
        q = " ".join(self.question.split())[:MAX_QUESTION_CHARS]
        return q


def _str(v, name: str, limit: int, required: bool = False) -> str:
    if v is None:
        v = ""
    if not isinstance(v, str):
        raise SchemaError(f"{name} must be a string")
    v = v.strip()
    if required and not v:
        raise SchemaError(f"{name} is required")
    if len(v) > limit:
        raise SchemaError(f"{name} longer than {limit} characters")
    return v


def _str_list(v, name: str) -> list[str]:
    if v is None:
        return []
    if not isinstance(v, list):
        raise SchemaError(f"{name} must be a list of strings")
    if len(v) > MAX_ITEMS:
        raise SchemaError(f"{name} has more than {MAX_ITEMS} items")
    return [_str(x, f"{name}[]", MAX_ITEM_CHARS, required=True) for x in v]


@dataclass
class AdvisoryExplanation:
    """An explanation split into stated facts and model interpretation."""

    summary: str
    evidence: list[str] = field(default_factory=list)  # facts quoted from the deterministic context
    interpretation: list[str] = field(default_factory=list)  # inference, labelled as such
    limitations: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d) -> "AdvisoryExplanation":
        if not isinstance(d, dict):
            raise SchemaError("expected a JSON object")
        return cls(summary=_str(d.get("summary"), "summary", MAX_TEXT_CHARS, required=True),
                   evidence=_str_list(d.get("evidence"), "evidence"),
                   interpretation=_str_list(d.get("interpretation"), "interpretation"),
                   limitations=_str_list(d.get("limitations"), "limitations"))

    def texts(self) -> list[str]:
        return [self.summary, *self.evidence, *self.interpretation, *self.limitations]

    def render(self) -> str:
        parts = [self.summary]
        for title, items in (("Evidence (from AeroMind output)", self.evidence),
                             ("Interpretation", self.interpretation), ("Limitations", self.limitations)):
            if items:
                parts.append(title + ":\n" + "\n".join(f"- {i}" for i in items))
        return "\n\n".join(parts)


@dataclass
class WorkOrderDraft:
    """A DRAFT work order. Only ``recommended_inspection`` and ``notes`` may come from the LLM."""

    aircraft: str
    component: str
    fault: str
    confidence: float
    evidence: list[str]
    rul_hours: dict  # p10 / p50 / p90
    risk_before_check: float
    decision: str
    maintenance_window: str
    required_part: str
    recommended_inspection: list[str]
    notes: str
    status: str = "DRAFT"
    reference: str = ""  # deterministic work-order number, if one exists

    def to_dict(self) -> dict:
        return asdict(self)

    def render(self) -> str:
        r = self.rul_hours
        lines = [f"WORK ORDER DRAFT ({self.status}){' ' + self.reference if self.reference else ''}",
                 f"Aircraft: {self.aircraft}  Component: {self.component}",
                 f"Fault: {self.fault} (confidence {self.confidence:.2f})",
                 "Evidence: " + ("; ".join(self.evidence) or "none recorded"),
                 f"RUL (FH): p10 {r['p10']:.0f} / p50 {r['p50']:.0f} / p90 {r['p90']:.0f}",
                 f"Risk of failure before next check: {self.risk_before_check:.1%}",
                 f"Decision (deterministic policy): {self.decision}",
                 f"Maintenance window: {self.maintenance_window}",
                 f"Required part: {self.required_part}",
                 "Recommended inspection:", *[f"  - {s}" for s in self.recommended_inspection],
                 f"Notes: {self.notes}"]
        return "\n".join(lines)


def parse_work_order_parts(d) -> tuple[list[str], str]:
    """The only two fields the LLM supplies for a work order."""
    if not isinstance(d, dict):
        raise SchemaError("expected a JSON object")
    steps = _str_list(d.get("recommended_inspection"), "recommended_inspection")
    if not steps:
        raise SchemaError("recommended_inspection is required")
    return steps, _str(d.get("notes"), "notes", MAX_TEXT_CHARS)


@dataclass
class FleetSummary:
    """Fleet counts and lists computed by code; ``narrative`` is the only LLM-written part."""

    aircraft_total: int
    status_counts: dict
    needs_attention: list[dict]
    sensor_health_problems: list[dict]
    maintenance_workload: dict
    recurring_patterns: list[str]
    narrative: AdvisoryExplanation | None = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class CopilotResponse:
    task: str
    tail: str
    deterministic: dict  # {"title", "lines"}: the structured AeroMind facts, shown separately in the UI
    text: str  # explanation text (AI-written, or a rule-based template when ai_generated is False)
    ai_generated: bool
    provider: str  # groq | ollama | deterministic
    model: str
    llm_status: str  # ONLINE | LOCAL | FALLBACK | UNAVAILABLE
    label: str
    structured: dict | None = None  # work_order or fleet summary payload
    warnings: list[str] = field(default_factory=list)
    simulated: bool = True
    note: str = SIM_NOTE

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)
