// Evidence deck for AeroMind (append to the main pitch deck). Every number comes from
// artifacts/deck_data.json, produced by prepare_deck_data.py from `python -m aeromind report`.
// Usage: node build_deck.js <deck_data.json> <screenshot.png|-> <out.pptx>
const fs = require("fs");
const pptxgen = require("pptxgenjs");

const [dataPath, shotPath, outPath] = process.argv.slice(2);
const D = JSON.parse(fs.readFileSync(dataPath, "utf8"));
const R = D.results;

const NAVY = "15213F", BLUE = "3257B8", CARD = "E9ECF2", MUTED = "5B6577", WHITE = "FFFFFF", AMBER = "C77700", ORANGE = "E0703A";
const TITLE = "Roboto Slab", BODY = "Roboto";

const pres = new pptxgen();
pres.layout = "LAYOUT_16x9"; // 10 x 5.625 in, same as the main deck
pres.title = "AeroMind prototype evidence";

const pct = (v, d = 1) => `${(v * 100).toFixed(d)}%`;
const sim = R.simulator.phase_aware_model_on_flight_phases;
const ims = R.ims && R.ims.bearings ? R.ims.bearings : null;

function title(slide, text, sub) {
  slide.addText(text, { x: 0.5, y: 0.3, w: 9, h: 0.55, fontFace: TITLE, fontSize: 22, bold: true, color: NAVY, margin: 0, fit: "shrink", isTextBox: true });
  if (sub) slide.addText(sub, { x: 0.5, y: 0.9, w: 9, h: 0.35, fontFace: BODY, fontSize: 12, color: MUTED, margin: 0, isTextBox: true });
}
function tag(slide, text, x, y, color) {
  slide.addText(text, { x, y, w: 1.75, h: 0.24, fontFace: BODY, fontSize: 8, bold: true, color: WHITE, align: "center",
    fill: { color }, shape: pres.shapes.ROUNDED_RECTANGLE, rectRadius: 0.05, margin: 0, isTextBox: true });
}
function footnote(slide, text) {
  slide.addText(text, { x: 0.5, y: 5.2, w: 9, h: 0.3, fontFace: BODY, fontSize: 8.5, color: MUTED, margin: 0, isTextBox: true });
}

// 1. Title -------------------------------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: NAVY };
  s.addText("AeroMind", { x: 0.6, y: 1.25, w: 8.8, h: 0.9, fontFace: TITLE, fontSize: 44, bold: true, color: WHITE, margin: 0, isTextBox: true });
  s.addText("Prototype evidence: what the working system does, and what we measured", { x: 0.6, y: 2.15, w: 8.8, h: 0.6,
    fontFace: BODY, fontSize: 18, color: "CFD6EA", margin: 0, isTextBox: true });
  s.addText("Project FY27-605244 · Tata InnoVent 2027 · AI at the Edge Solutions for Aerospace", { x: 0.6, y: 3.0, w: 8.8, h: 0.4,
    fontFace: BODY, fontSize: 12, color: "9AA6C4", margin: 0, isTextBox: true });
  s.addText("Every number in this section is regenerated by `python -m aeromind report`. Aircraft data is simulated unless marked REAL DATA.",
    { x: 0.6, y: 4.6, w: 8.8, h: 0.5, fontFace: BODY, fontSize: 10, color: "9AA6C4", margin: 0, isTextBox: true });
}

// 2. Pipeline ----------------------------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: WHITE };
  title(s, "One second of sensor data in, one decision out", "Runs on the aircraft for every 1-second window; only the advisory is downlinked");
  const steps = [["Sensor health", "stuck, drift, spikes,\ndropout, range"], ["Fusion", "21 features incl.\nOAT and altitude"],
    ["Anomaly score", "Isolation Forest\n+ autoencoder"], ["Persistence gate", "5 of 8 windows"],
    ["Fault class", "gradient-boosted trees\non context residuals"], ["RUL + interval", "p10 / p50 / p90,\nconformal"],
    ["Evidence + ACARS", "bearing defect\nfrequencies, ≤220 chars"]];
  const w = 1.18, gap = 0.12, y = 1.65;
  steps.forEach(([h, d], i) => {
    const x = 0.5 + i * (w + gap);
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h: 1.35, fill: { color: i === 0 ? "EDE6F7" : CARD }, rectRadius: 0.08, line: { color: CARD } });
    s.addText(h, { x: x + 0.08, y: y + 0.12, w: w - 0.16, h: 0.45, fontFace: BODY, fontSize: 10.5, bold: true, color: NAVY, margin: 0, valign: "top", isTextBox: true });
    s.addText(d, { x: x + 0.08, y: y + 0.6, w: w - 0.16, h: 0.7, fontFace: BODY, fontSize: 8.5, color: MUTED, margin: 0, valign: "top", isTextBox: true });
    if (i < steps.length - 1) s.addText("›", { x: x + w - 0.02, y: y + 0.45, w: gap + 0.04, h: 0.4, fontSize: 16, color: BLUE, align: "center", margin: 0, isTextBox: true });
  });
  s.addText("On the ground", { x: 0.5, y: 3.35, w: 3, h: 0.35, fontFace: TITLE, fontSize: 14, bold: true, color: NAVY, margin: 0, isTextBox: true });
  const ground = [["Decision engine", "P(failure before next check) → ground now / replace at next check / defer"],
    ["Work order", "task, part, window, evidence and the ACARS text"],
    ["Fleet ROI", "reactive vs fixed-interval vs AeroMind, with a sensitivity range"],
    ["Signed OTA", "Ed25519 + SHA-256; tampered models rejected, rollback"]];
  ground.forEach(([h, d], i) => {
    const x = 0.5 + i * 2.27;
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y: 3.78, w: 2.13, h: 1.2, fill: { color: "DCE5F8" }, rectRadius: 0.08, line: { color: "DCE5F8" } });
    s.addText(h, { x: x + 0.1, y: 3.88, w: 1.95, h: 0.3, fontFace: BODY, fontSize: 11, bold: true, color: NAVY, margin: 0, isTextBox: true });
    s.addText(d, { x: x + 0.1, y: 4.2, w: 1.95, h: 0.72, fontFace: BODY, fontSize: 9, color: MUTED, margin: 0, valign: "top", isTextBox: true });
  });
}

// 3. Headline numbers -------------------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: WHITE };
  title(s, "Measured, not promised", "Headline results from the prototype");
  const sh = R.sensor_health;
  const falseComp = Object.values(sh.cases).reduce((t, c) => t + c.component_advisories_with_health, 0);
  const fp = R.flight_phases;
  const b = R.edge_benchmark;
  const stats = [
    [ims ? `${ims.bearing_1.lead_time_hours.toFixed(1)} h` : "n/a", "warning before a real bearing's outer-race failure", "REAL DATA · NASA IMS", ORANGE],
    [pct(fp.healthy_phase_aware_model.gate_open), `anomaly gate open on healthy flights (${pct(fp.healthy_steady_model.gate_open)} without flight-phase awareness)`, "SIMULATED", BLUE],
    [String(falseComp), `false component alarms from ${Object.keys(sh.cases).length} kinds of injected sensor failure`, "SIMULATED", BLUE],
    [sim.first_classified_correct.oil_contamination, "oil contamination correct at first classification under flight phases", "SIMULATED", BLUE],
    [`${R.acars.max_chars}/${R.acars.limit}`, "characters: every advisory fits one ACARS downlink block", "SIMULATED", BLUE],
    [`${b.latency.full_window_process.mean_ms.toFixed(1)} ms`, `per window on one CPU thread; ${(b.total_kb / 1024).toFixed(1)} MB of models`, "CPU, NOT JETSON", AMBER],
  ];
  stats.forEach(([v, label, t, c], i) => {
    const col = i % 3, row = Math.floor(i / 3), x = 0.5 + col * 3.05, y = 1.45 + row * 1.85;
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w: 2.85, h: 1.65, fill: { color: CARD }, rectRadius: 0.08, line: { color: CARD } });
    tag(s, t, x + 0.15, y + 0.15, c);
    s.addText(v, { x: x + 0.15, y: y + 0.45, w: 2.55, h: 0.6, fontFace: TITLE, fontSize: 28, bold: true, color: NAVY, margin: 0, isTextBox: true });
    s.addText(label, { x: x + 0.15, y: y + 1.05, w: 2.55, h: 0.55, fontFace: BODY, fontSize: 9.5, color: MUTED, margin: 0, valign: "top", isTextBox: true });
  });
}

// 4. Real data ---------------------------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: WHITE };
  title(s, "On real data, it sees the failure coming", "Left: NASA IMS bearing run-to-failure (REAL). Right: NASA C-MAPSS turbofan RUL benchmark");
  if (D.ims_curve) {
    const c = D.ims_curve, others = c.hours.map((_, i) => Math.max(c.bpfo_snr[1][i], c.bpfo_snr[2][i], c.bpfo_snr[3][i]));
    s.addChart(pres.charts.LINE, [
      { name: "Bearing 1 (failed: outer race)", labels: c.hours.map((h) => h.toFixed(0)), values: c.bpfo_snr[0] },
      { name: "Bearings 2-4 (strongest)", labels: c.hours.map((h) => h.toFixed(0)), values: others },
    ], { x: 0.4, y: 1.35, w: 4.7, h: 3.35, showTitle: true, title: "Outer-race signature (BPFO envelope SNR) vs test hour",
      titleFontSize: 11, titleColor: NAVY, chartColors: [ORANGE, "9AA6C4"], lineSize: 2, lineDataSymbol: "none",
      showLegend: true, legendPos: "b", legendFontSize: 9, catAxisLabelFontSize: 8, valAxisLabelFontSize: 8,
      catAxisLabelColor: MUTED, valAxisLabelColor: MUTED, valGridLine: { color: "E3E6EE", size: 0.5 }, catGridLine: { style: "none" },
      catAxisLabelFrequency: 20 });
  }
  const cm = R.cmapss_hgb_conformal, lstm = R.lstm && R.lstm.cmapss_conformal;
  if (cm && !cm.unavailable) {
    const subs = Object.keys(cm);
    const series = [];
    if (lstm) series.push({ name: "AeroMind LSTM", labels: subs, values: subs.map((k) => lstm[k].rmse) });
    series.push({ name: "AeroMind trees", labels: subs, values: subs.map((k) => cm[k].rmse) });
    series.push({ name: "Constant baseline", labels: subs, values: subs.map((k) => cm[k].constant_baseline_rmse) });
    s.addChart(pres.charts.BAR, series, { x: 5.25, y: 1.35, w: 4.35, h: 3.35, barDir: "col", barGrouping: "clustered",
      showTitle: true, title: "RUL error, RMSE in cycles (lower is better)", titleFontSize: 11, titleColor: NAVY,
      chartColors: lstm ? [BLUE, "8FA7DE", "C9CFDB"] : ["8FA7DE", "C9CFDB"], showValue: true, dataLabelPosition: "outEnd",
      dataLabelFontSize: 7, dataLabelFormatCode: "0", showLegend: true, legendPos: "b", legendFontSize: 9,
      catAxisLabelFontSize: 9, valAxisLabelFontSize: 8, catAxisLabelColor: MUTED, valAxisLabelColor: MUTED,
      valGridLine: { color: "E3E6EE", size: 0.5 }, catGridLine: { style: "none" } });
  }
  const loc = R.ims && R.ims.localisation ? R.ims.localisation.share_of_snapshots_strongest.bearing_1 : null;
  footnote(s, ims ? `IMS: alarm and BPFO evidence ${ims.bearing_1.lead_time_hours.toFixed(1)} h before the end of the test; bearing 1 has the strongest signature in ${pct(loc)} of snapshots once it appears. C-MAPSS: official test split, 3 seeds; C-MAPSS engines are simulated by NASA.` : "");
}

// 5. Live demo ---------------------------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: WHITE };
  title(s, "Live demo: break the aircraft, watch it respond", "python -m aeromind serve · six simulated aircraft · works offline");
  if (shotPath && shotPath !== "-" && fs.existsSync(shotPath)) {
    s.addImage({ path: shotPath, x: 0.45, y: 1.35, w: 5.8, h: 3.625 });
  }
  const steps = ["Inject bearing wear: score rises, gate opens, fault named, RUL falls, physics evidence, decision, work order, ACARS",
    "Fail a temperature sensor: SENSOR_FAULT, channel masked, no false gearbox alarm",
    "Push a signed model: accepted. Push a tampered one: rejected, fleet stays on the last valid model",
    "Drag the what-if slider: the decision changes with the time to the next check"];
  steps.forEach((t, i) => {
    const y = 1.35 + i * 0.92;
    s.addShape(pres.shapes.OVAL, { x: 6.5, y, w: 0.36, h: 0.36, fill: { color: BLUE }, line: { color: BLUE } });
    s.addText(String(i + 1), { x: 6.5, y, w: 0.36, h: 0.36, fontFace: BODY, fontSize: 11, bold: true, color: WHITE, align: "center", valign: "middle", margin: 0, isTextBox: true });
    s.addText(t, { x: 7.0, y: y - 0.05, w: 2.6, h: 0.85, fontFace: BODY, fontSize: 9.5, color: NAVY, margin: 0, valign: "top", isTextBox: true });
  });
}

// 6. Business case ----------------------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: WHITE };
  title(s, "The business case holds under harsh assumptions", "Maintenance cost vs reactive, 30 aircraft × 3,000 flight hours (simulation)");
  const sens = R.roi.sensitivity;
  const labels = ["As measured", "Weak detection,\nshort warning", "AOG $10k/h", "All harsh"];
  s.addChart(pres.charts.BAR, [
    { name: "AeroMind", labels, values: sens.map((x) => -x.aeromind_cost_vs_reactive_pct) },
    { name: "Fixed interval", labels, values: sens.map((x) => -x.fixed_interval_cost_vs_reactive_pct) },
  ], { x: 0.4, y: 1.35, w: 5.6, h: 3.6, barDir: "col", barGrouping: "clustered", showTitle: true,
    title: "Cost saving vs reactive maintenance (%)", titleFontSize: 11, titleColor: NAVY, chartColors: [BLUE, "C9CFDB"],
    showValue: true, dataLabelPosition: "outEnd", dataLabelFontSize: 8, dataLabelFormatCode: "0", showLegend: true, legendPos: "b",
    legendFontSize: 9, catAxisLabelFontSize: 8.5, valAxisLabelFontSize: 8, catAxisLabelColor: MUTED, valAxisLabelColor: MUTED,
    valGridLine: { color: "E3E6EE", size: 0.5 }, catGridLine: { style: "none" } });
  const p = R.roi.policies;
  const facts = [
    `Reactive: ${p.reactive.unscheduled_removals} unscheduled removals, ${p.reactive.aog_hours} AOG hours`,
    `AeroMind as measured: ${p.aeromind.unscheduled_removals} unscheduled, ${p.aeromind.aog_hours} AOG hours, ${p.aeromind.parts_used} parts (fixed interval: ${p.fixed_interval.parts_used})`,
    "Harsh case: 67% detection, 10% of the warning time, 5 false advisories per 1,000 windows, AOG at $10k/h",
    "Detection and warning times are measured; costs and failure rates are labelled assumptions",
  ];
  s.addText(facts.map((t, i) => ({ text: t, options: { bullet: true, breakLine: i < facts.length - 1 } })),
    { x: 6.25, y: 1.45, w: 3.35, h: 3.4, fontFace: BODY, fontSize: 10, color: NAVY, paraSpaceAfter: 8, valign: "top", margin: 0, isTextBox: true });
}

// 7. Fleet learning + security -----------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: WHITE };
  title(s, "The fleet learns together, without sharing raw data", "Each aircraft has seen only 2 of 5 fault types; models share weights only (federated averaging)");
  const f = R.federated_rare_fault;
  if (f) {
    const labels = ["Fault types seen locally", "Fault types never seen locally"];
    s.addChart(pres.charts.BAR, [
      { name: "Local only", labels, values: [f.local.seen_fault_accuracy * 100, f.local.unseen_fault_accuracy * 100] },
      { name: "Federated", labels, values: [f.federated.seen_fault_accuracy * 100, f.federated.unseen_fault_accuracy * 100] },
      { name: "Pooled raw data (upper bound)", labels, values: [f.centralised_upper_bound.seen_fault_accuracy * 100, f.centralised_upper_bound.unseen_fault_accuracy * 100] },
    ], { x: 0.4, y: 1.4, w: 5.6, h: 3.5, barDir: "col", barGrouping: "clustered", showTitle: true,
      title: `Classification accuracy (%), mean of ${f.seeds} seeds`, titleFontSize: 11, titleColor: NAVY,
      chartColors: ["C9CFDB", BLUE, "8FA7DE"], showValue: true, dataLabelPosition: "outEnd", dataLabelFontSize: 8, dataLabelFormatCode: "0",
      valAxisMinVal: 0, valAxisMaxVal: 110, showLegend: true, legendPos: "b", legendFontSize: 9, catAxisLabelFontSize: 9, valAxisLabelFontSize: 8,
      catAxisLabelColor: MUTED, valAxisLabelColor: MUTED, valGridLine: { color: "E3E6EE", size: 0.5 }, catGridLine: { style: "none" } });
  }
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: 6.25, y: 1.45, w: 3.35, h: 3.4, fill: { color: CARD }, rectRadius: 0.08, line: { color: CARD } });
  s.addText("Secure model updates", { x: 6.45, y: 1.6, w: 3, h: 0.35, fontFace: TITLE, fontSize: 13, bold: true, color: NAVY, margin: 0, isTextBox: true });
  const sec = ["Model packages signed with Ed25519", "Every model file pinned by SHA-256 in the signed manifest",
    "Tampered package rejected before install; fleet keeps the last valid model", "One-click rollback to the previous version"];
  s.addText(sec.map((t, i) => ({ text: t, options: { bullet: true, breakLine: i < sec.length - 1 } })),
    { x: 6.45, y: 2.05, w: 3.0, h: 2.7, fontFace: BODY, fontSize: 10, color: NAVY, paraSpaceAfter: 8, valign: "top", margin: 0, isTextBox: true });
}

// 8. Limits and next steps --------------------------------------------------------------
{
  const s = pres.addSlide(); s.background = { color: NAVY };
  s.addText("What is not proven yet, and what comes next", { x: 0.5, y: 0.4, w: 9, h: 0.6, fontFace: TITLE, fontSize: 24, bold: true, color: WHITE, margin: 0, isTextBox: true });
  const limits = ["No flight data: the fleet is simulated; real-data evidence is one bearing rig (IMS) and NASA's simulated engines (C-MAPSS)",
    "Not yet run on a Jetson or TensorRT; timings are CPU", "No certification work; decisions follow a configurable prototype policy",
    "Costs and failure rates in the ROI model are assumptions"];
  const next = ["Jetson build and power/latency measurement (kit ready)", "Real multi-sensor data with an operator or MRO partner",
    "Hardware-in-the-loop bench with a vibration sensor", "Integration pilot with an MRO work-order system"];
  [["Limits", limits, 0.5], ["Next", next, 5.1]].forEach(([h, items, x]) => {
    s.addText(h, { x, y: 1.25, w: 4.3, h: 0.4, fontFace: TITLE, fontSize: 15, bold: true, color: "9FB6EE", margin: 0, isTextBox: true });
    s.addText(items.map((t, i) => ({ text: t, options: { bullet: true, breakLine: i < items.length - 1 } })),
      { x, y: 1.75, w: 4.3, h: 3.2, fontFace: BODY, fontSize: 11, color: WHITE, paraSpaceAfter: 10, valign: "top", margin: 0, isTextBox: true });
  });
}

pres.writeFile({ fileName: outPath }).then(() => console.log(`wrote ${outPath}`));
